/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpeningsRouteImport } from './routes/openings'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles/index'
import { Route as OpeningsIndexRouteImport } from './routes/openings/index'
import { Route as PuzzlesPuzzleIdRouteImport } from './routes/puzzles/$puzzleId'
import { Route as OpeningsBrowseRouteImport } from './routes/openings/browse'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as AccountPathnameRouteImport } from './routes/account/$pathname'
import { Route as AuthGamesRouteImport } from './routes/_auth/games'
import { Route as AuthGamesIndexRouteImport } from './routes/_auth/games/index'
import { Route as AuthGamesListRouteImport } from './routes/_auth/games/list'
import { Route as AuthGamesDashboardRouteImport } from './routes/_auth/games/dashboard'
import { Route as AuthGamesGameIdRouteImport } from './routes/_auth/games/$gameId'

const OpeningsRoute = OpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsIndexRoute = OpeningsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpeningsRoute,
} as any)
const PuzzlesPuzzleIdRoute = PuzzlesPuzzleIdRouteImport.update({
  id: '/puzzles/$puzzleId',
  path: '/puzzles/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsBrowseRoute = OpeningsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => OpeningsRoute,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGamesRoute = AuthGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGamesIndexRoute = AuthGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGamesRoute,
} as any)
const AuthGamesListRoute = AuthGamesListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthGamesRoute,
} as any)
const AuthGamesDashboardRoute = AuthGamesDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthGamesRoute,
} as any)
const AuthGamesGameIdRoute = AuthGamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => AuthGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/openings': typeof OpeningsRouteWithChildren
  '/games': typeof AuthGamesRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/openings/browse': typeof OpeningsBrowseRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdRoute
  '/openings/': typeof OpeningsIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/games/$gameId': typeof AuthGamesGameIdRoute
  '/games/dashboard': typeof AuthGamesDashboardRoute
  '/games/list': typeof AuthGamesListRoute
  '/games/': typeof AuthGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/openings/browse': typeof OpeningsBrowseRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdRoute
  '/openings': typeof OpeningsIndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/games/$gameId': typeof AuthGamesGameIdRoute
  '/games/dashboard': typeof AuthGamesDashboardRoute
  '/games/list': typeof AuthGamesListRoute
  '/games': typeof AuthGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/openings': typeof OpeningsRouteWithChildren
  '/_auth/games': typeof AuthGamesRouteWithChildren
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/openings/browse': typeof OpeningsBrowseRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdRoute
  '/openings/': typeof OpeningsIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/_auth/games/$gameId': typeof AuthGamesGameIdRoute
  '/_auth/games/dashboard': typeof AuthGamesDashboardRoute
  '/_auth/games/list': typeof AuthGamesListRoute
  '/_auth/games/': typeof AuthGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/openings'
    | '/games'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/openings/browse'
    | '/puzzles/$puzzleId'
    | '/openings/'
    | '/puzzles/'
    | '/games/$gameId'
    | '/games/dashboard'
    | '/games/list'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/openings/browse'
    | '/puzzles/$puzzleId'
    | '/openings'
    | '/puzzles'
    | '/games/$gameId'
    | '/games/dashboard'
    | '/games/list'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/openings'
    | '/_auth/games'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/openings/browse'
    | '/puzzles/$puzzleId'
    | '/openings/'
    | '/puzzles/'
    | '/_auth/games/$gameId'
    | '/_auth/games/dashboard'
    | '/_auth/games/list'
    | '/_auth/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OpeningsRoute: typeof OpeningsRouteWithChildren
  AccountPathnameRoute: typeof AccountPathnameRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  PuzzlesPuzzleIdRoute: typeof PuzzlesPuzzleIdRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openings': {
      id: '/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof OpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/': {
      id: '/openings/'
      path: '/'
      fullPath: '/openings/'
      preLoaderRoute: typeof OpeningsIndexRouteImport
      parentRoute: typeof OpeningsRoute
    }
    '/puzzles/$puzzleId': {
      id: '/puzzles/$puzzleId'
      path: '/puzzles/$puzzleId'
      fullPath: '/puzzles/$puzzleId'
      preLoaderRoute: typeof PuzzlesPuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/browse': {
      id: '/openings/browse'
      path: '/browse'
      fullPath: '/openings/browse'
      preLoaderRoute: typeof OpeningsBrowseRouteImport
      parentRoute: typeof OpeningsRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/games': {
      id: '/_auth/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthGamesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/games/': {
      id: '/_auth/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthGamesIndexRouteImport
      parentRoute: typeof AuthGamesRoute
    }
    '/_auth/games/list': {
      id: '/_auth/games/list'
      path: '/list'
      fullPath: '/games/list'
      preLoaderRoute: typeof AuthGamesListRouteImport
      parentRoute: typeof AuthGamesRoute
    }
    '/_auth/games/dashboard': {
      id: '/_auth/games/dashboard'
      path: '/dashboard'
      fullPath: '/games/dashboard'
      preLoaderRoute: typeof AuthGamesDashboardRouteImport
      parentRoute: typeof AuthGamesRoute
    }
    '/_auth/games/$gameId': {
      id: '/_auth/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthGamesGameIdRouteImport
      parentRoute: typeof AuthGamesRoute
    }
  }
}

interface AuthGamesRouteChildren {
  AuthGamesGameIdRoute: typeof AuthGamesGameIdRoute
  AuthGamesDashboardRoute: typeof AuthGamesDashboardRoute
  AuthGamesListRoute: typeof AuthGamesListRoute
  AuthGamesIndexRoute: typeof AuthGamesIndexRoute
}

const AuthGamesRouteChildren: AuthGamesRouteChildren = {
  AuthGamesGameIdRoute: AuthGamesGameIdRoute,
  AuthGamesDashboardRoute: AuthGamesDashboardRoute,
  AuthGamesListRoute: AuthGamesListRoute,
  AuthGamesIndexRoute: AuthGamesIndexRoute,
}

const AuthGamesRouteWithChildren = AuthGamesRoute._addFileChildren(
  AuthGamesRouteChildren,
)

interface AuthRouteChildren {
  AuthGamesRoute: typeof AuthGamesRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGamesRoute: AuthGamesRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OpeningsRouteChildren {
  OpeningsBrowseRoute: typeof OpeningsBrowseRoute
  OpeningsIndexRoute: typeof OpeningsIndexRoute
}

const OpeningsRouteChildren: OpeningsRouteChildren = {
  OpeningsBrowseRoute: OpeningsBrowseRoute,
  OpeningsIndexRoute: OpeningsIndexRoute,
}

const OpeningsRouteWithChildren = OpeningsRoute._addFileChildren(
  OpeningsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OpeningsRoute: OpeningsRouteWithChildren,
  AccountPathnameRoute: AccountPathnameRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  PuzzlesPuzzleIdRoute: PuzzlesPuzzleIdRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
