/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainRouteImport } from './routes/train'
import { Route as OpeningsRouteImport } from './routes/openings'
import { Route as DevPreviewRouteImport } from './routes/dev-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles/index'
import { Route as OpeningsIndexRouteImport } from './routes/openings/index'
import { Route as PuzzlesPuzzleIdRouteImport } from './routes/puzzles/$puzzleId'
import { Route as OpeningsBrowseRouteImport } from './routes/openings/browse'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as AccountPathnameRouteImport } from './routes/account/$pathname'

const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsRoute = OpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewRoute = DevPreviewRouteImport.update({
  id: '/dev-preview',
  path: '/dev-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsIndexRoute = OpeningsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpeningsRoute,
} as any)
const PuzzlesPuzzleIdRoute = PuzzlesPuzzleIdRouteImport.update({
  id: '/puzzles/$puzzleId',
  path: '/puzzles/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsBrowseRoute = OpeningsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => OpeningsRoute,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-preview': typeof DevPreviewRoute
  '/openings': typeof OpeningsRouteWithChildren
  '/train': typeof TrainRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/openings/browse': typeof OpeningsBrowseRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdRoute
  '/openings/': typeof OpeningsIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-preview': typeof DevPreviewRoute
  '/train': typeof TrainRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/openings/browse': typeof OpeningsBrowseRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdRoute
  '/openings': typeof OpeningsIndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-preview': typeof DevPreviewRoute
  '/openings': typeof OpeningsRouteWithChildren
  '/train': typeof TrainRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/openings/browse': typeof OpeningsBrowseRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdRoute
  '/openings/': typeof OpeningsIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-preview'
    | '/openings'
    | '/train'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/openings/browse'
    | '/puzzles/$puzzleId'
    | '/openings/'
    | '/puzzles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-preview'
    | '/train'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/openings/browse'
    | '/puzzles/$puzzleId'
    | '/openings'
    | '/puzzles'
  id:
    | '__root__'
    | '/'
    | '/dev-preview'
    | '/openings'
    | '/train'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/openings/browse'
    | '/puzzles/$puzzleId'
    | '/openings/'
    | '/puzzles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevPreviewRoute: typeof DevPreviewRoute
  OpeningsRoute: typeof OpeningsRouteWithChildren
  TrainRoute: typeof TrainRoute
  AccountPathnameRoute: typeof AccountPathnameRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  PuzzlesPuzzleIdRoute: typeof PuzzlesPuzzleIdRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings': {
      id: '/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof OpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-preview': {
      id: '/dev-preview'
      path: '/dev-preview'
      fullPath: '/dev-preview'
      preLoaderRoute: typeof DevPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/': {
      id: '/openings/'
      path: '/'
      fullPath: '/openings/'
      preLoaderRoute: typeof OpeningsIndexRouteImport
      parentRoute: typeof OpeningsRoute
    }
    '/puzzles/$puzzleId': {
      id: '/puzzles/$puzzleId'
      path: '/puzzles/$puzzleId'
      fullPath: '/puzzles/$puzzleId'
      preLoaderRoute: typeof PuzzlesPuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/browse': {
      id: '/openings/browse'
      path: '/browse'
      fullPath: '/openings/browse'
      preLoaderRoute: typeof OpeningsBrowseRouteImport
      parentRoute: typeof OpeningsRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpeningsRouteChildren {
  OpeningsBrowseRoute: typeof OpeningsBrowseRoute
  OpeningsIndexRoute: typeof OpeningsIndexRoute
}

const OpeningsRouteChildren: OpeningsRouteChildren = {
  OpeningsBrowseRoute: OpeningsBrowseRoute,
  OpeningsIndexRoute: OpeningsIndexRoute,
}

const OpeningsRouteWithChildren = OpeningsRoute._addFileChildren(
  OpeningsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevPreviewRoute: DevPreviewRoute,
  OpeningsRoute: OpeningsRouteWithChildren,
  TrainRoute: TrainRoute,
  AccountPathnameRoute: AccountPathnameRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  PuzzlesPuzzleIdRoute: PuzzlesPuzzleIdRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
