"""baseline

Revision ID: 0dc881a801c0
Revises: 
Create Date: 2026-06-19 16:20:25.575505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dc881a801c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_migrations')
    op.drop_index(op.f('idx_games_played_at'), table_name='games')
    op.drop_index(op.f('idx_games_user_color'), table_name='games')
    op.drop_index(op.f('idx_games_user_eco'), table_name='games')
    op.drop_index(op.f('idx_games_user_id'), table_name='games')
    op.drop_index(op.f('idx_games_user_result'), table_name='games')
    op.drop_index(op.f('idx_games_user_time_class'), table_name='games')
    op.create_index(op.f('ix_games_played_at'), 'games', ['played_at'], unique=False)
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.drop_index(op.f('idx_comments_position'), table_name='position_comments')
    op.drop_index(op.f('idx_position_move_stats_moves'), table_name='position_move_stats', postgresql_using='gin')
    op.drop_index(op.f('idx_position_moves_from'), table_name='position_moves')
    op.drop_index(op.f('idx_position_moves_to'), table_name='position_moves')
    op.drop_constraint(op.f('position_moves_from_position_id_san_key'), 'position_moves', type_='unique')
    op.drop_index(op.f('idx_positions_name'), table_name='positions', postgresql_using='gin')
    op.drop_constraint(op.f('rc_user_position_unique'), 'repertoire_cards', type_='unique')
    op.drop_index(op.f('repertoire_cards_user_id_due_idx'), table_name='repertoire_cards')
    op.drop_index(op.f('idx_user_positions_user'), table_name='user_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_positions_user'), 'user_positions', ['user_id'], unique=False)
    op.create_index(op.f('repertoire_cards_user_id_due_idx'), 'repertoire_cards', ['user_id', 'due'], unique=False)
    op.create_unique_constraint(op.f('rc_user_position_unique'), 'repertoire_cards', ['user_id', 'position_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_positions_name'), 'positions', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(name, ''::text))")], unique=False, postgresql_using='gin')
    op.create_unique_constraint(op.f('position_moves_from_position_id_san_key'), 'position_moves', ['from_position_id', 'san'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_position_moves_to'), 'position_moves', ['to_position_id'], unique=False)
    op.create_index(op.f('idx_position_moves_from'), 'position_moves', ['from_position_id'], unique=False)
    op.create_index(op.f('idx_position_move_stats_moves'), 'position_move_stats', ['moves'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_comments_position'), 'position_comments', ['position_id'], unique=False)
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_index(op.f('ix_games_played_at'), table_name='games')
    op.create_index(op.f('idx_games_user_time_class'), 'games', ['user_id', 'time_class'], unique=False)
    op.create_index(op.f('idx_games_user_result'), 'games', ['user_id', 'result'], unique=False)
    op.create_index(op.f('idx_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_index(op.f('idx_games_user_eco'), 'games', ['user_id', 'eco'], unique=False)
    op.create_index(op.f('idx_games_user_color'), 'games', ['user_id', 'user_color'], unique=False)
    op.create_index(op.f('idx_games_played_at'), 'games', [sa.literal_column('played_at DESC')], unique=False)
    op.create_table('_migrations',
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('filename', name=op.f('_migrations_pkey'))
    )
    # ### end Alembic commands ###
