"""drop_user_positions

Revision ID: 1f71880a707e
Revises: 0dc881a801c0
Create Date: 2026-06-19 16:23:50.303891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f71880a707e'
down_revision: Union[str, Sequence[str], None] = '0dc881a801c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_positions',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fen', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fen'], ['positions.fen'], name=op.f('user_positions_fen_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'fen', name=op.f('user_positions_pkey'))
    )
    # ### end Alembic commands ###
